language: node_js
node_js:
- 12
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "pentimento-test";' -U postgres
script:
- npm test
- npm run build-client
# deploy:
#   api_key:
#     secure: QbX9BGjdlqVsodIOsuSLUiZHu16dFsYFNRXtgeRAUyENR1Horghp4cQPxAcy4BtEJXA0o1VKzNP0NJLhaMiEzqLprex0oQRvj2+ivAaALV1mbJxdMx2G8SM3IVuOkXnWVTvrgM2Xol3fEoqEjFjTwKYlHBh5MVIE8IqMoaKR+R8ABwtqeRZDi4A0Loj0+ijodfP9Kef65J7wpBJrAhIpXH+1jf1PJAC3HnyknfO1l1DuwW5MnHmG1V6+kLP4HVV0YUH+UixUM7v966eFxE9E8SbED7HtNJC8O++eqpRS2DapRqRbH83An8kWD6kl6nvNYxJFis9+Xyui2yZa8pGTwhRJWDLgc4dCzIlM5/W22fH4ZuYzg93oU4cG57oeOVb85boR4WipmXTydO+QpABqfPHCHJ9/SzA1TGDnu66SCJRNQYI7Y5NaYc2Yk/uxuLrMxQ69IVNPePdZKT0W40ueNuRuchZsuZCIAdjUU624SfMWPXdGv8Vs82nWArPpeLLKK/4mht+CqU+rJCQIkJODBNGhvHT+RfTz2SQnTnnubDDE+vK4M6C2RuhPDouF3DUEEzFHNyhmfZql3HTm6wwmZc7djzttZoK3PlCToNdMHNBUB78qDMxMKbMvp1v7OqeH217wSiHtfaGbf8QzBa1C0SWB9wq6K40dJQtk0y7oID8=
